title: Sasso dopo sasso
author: 
  name: Katia Grillo, Arianna Masciolini e Velia Sajeva
description: > 
  Rimarrete di sasso!

header_pages:
  - catalogo.md
  - ringraziamenti.md

show_excerpts: false

remote_theme: jekyll/minima

minima:
  skin: dark
  date_format: "%-d %B %Y"